version: '2'

services:

  alpine:
    build: .
    privileged: true
    volumes:
      - mountedshare:/mnt
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'

  test:
    build: ./test
    privileged: true
    volumes:
      - mountedshare:/data

volumes:
  mountedshare:
